#!/usr/bin/env python3
"""Regenerate js/data/sp500.js: every S&P 500 company, its sector and market cap.

Market caps come from stockanalysis.com, sectors from Wikipedia. Dual share
classes (GOOG, FOX, NWS) fold into their sibling so each company is one house.
Run from the repo root: python3 tools/fetch_sp500.py
"""
import datetime, html, json, re, urllib.request

UA = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/126 Safari/537.36'}
DUAL = {'GOOG': 'GOOGL', 'FOX': 'FOXA', 'NWS': 'NWSA'}
SUFFIXES = [' (Class A)', ' (Class B)', ' (Class C)', ',', ' Inc.', ' Inc', ' Incorporated', ' Corporation',
            ' Corp.', ' Corp', ' Companies', ' Company', ' Co.', ' plc', ' PLC', ' N.V.', ' Ltd.', ' Limited',
            ' Holdings', ' Holding', ' Group', ' S.A.', ' AG', ' SE', ' L.P.', ' Trust']


def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA)).read().decode()


def short(name):
    name = name.removeprefix('The ')
    changed = True
    while changed:
        changed = False
        for s in SUFFIXES:
            if name.endswith(s):
                name, changed = name[: -len(s)].strip(), True
    return name


def main():
    sa = get('https://stockanalysis.com/list/sp-500-stocks/')
    rows = re.findall(r'\{no:\d+,s:"([^"]+)",n:"[^"]*",marketCap:([\d.e+]+),', sa)
    wiki = get('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
    table = wiki[wiki.index('id="constituents"'):]
    table = table[: table.index('</table>')]
    text = lambda s: html.unescape(re.sub('<[^>]+>', '', s)).strip()
    info = {}
    for tr in table.split('<tr')[2:]:
        tds = re.findall(r'<td[^>]*>(.*?)</td>', tr, re.S)
        if len(tds) >= 3:
            info[text(tds[0]).replace('.', '-')] = (short(text(tds[1])), text(tds[2]))

    caps = {}
    for ticker, cap in rows:
        # Each share class row already reports the whole company's cap, so keep one, not the sum
        key = DUAL.get(ticker, ticker)
        caps[key] = max(caps.get(key, 0), float(cap))
    out = sorted(((t, *info[t.replace('.', '-')], c) for t, c in caps.items()), key=lambda r: -r[3])
    assert len(out) >= 495, f'only {len(out)} companies parsed, a page layout probably changed'

    lines = [f'  [{json.dumps(t)}, {json.dumps(n)}, {json.dumps(s)}, {c:.4g}],' for t, n, s, c in out]
    open('js/data/sp500.js', 'w').write(
        '// Generated by tools/fetch_sp500.py, do not edit by hand.\n'
        '// [ticker, name, GICS sector, market cap USD], largest first.\n'
        f"export const AS_OF = '{datetime.date.today()}';\n"
        'export const SP500 = [\n' + '\n'.join(lines) + '\n];\n')
    print(len(out), 'companies written')


main()
